FROM golang:1.22-alpine AS build
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN go build -o /rds ./cmd/rds

FROM alpine:3.19
RUN apk --no-cache add ca-certificates
COPY --from=build /rds /rds
EXPOSE 6062
ENTRYPOINT ["/rds", "-port", "6062"]
